### PR TITLE
Use & operator from Data.Function

### PR DESCRIPTION
**Pull request by amarpotghan**

### CODE REVIEW

**Comment by Gabriella439** [comment]
Thanks!  Great idea to make sure that this doesn't conflict with `Data.Function.&`

**Comment by amarpotghan** [comment]
Thank you for great libraries and blogs :) I was thinking if it makes sense to not reexport (&) at all and update documentation accordingly. Most of the lens libraries (lens, lens-family, microlens at least) (re)export this function. What do you think?

**Comment by Gabriella439** [comment]
I think it's fine to re-export, especially now that it reuses `Data.Function.&` so it won't clash with other exports.  I generally try to reduce the number of imports for users when it's easy to do so

**Comment by amarpotghan** [comment]
Sure, that makes sense.

**Pull request merged**
