### PR TITLE
Added `_default` for inexhaustive pattern matches.

### PR DESCRIPTION
**Pull request by echatav**
See Issue #4.

### CODE REVIEW

**Comment by echatav** [comment]
Added `_default` to exports

**Comment by Gabriella439** [comment]
Beautiful!  Thank you :)

I'll upload this to Hackage

**Comment by echatav** [comment]
Oh no, looking on hackage it looks like I messed up the haddocs :-(

It needs an extra commented out line after line 74. Sorry!

**Comment by Gabriella439** [comment]
It's alright!  Can you submit a pull request to fix it?

**Comment by echatav** [comment]
Sure!

**Pull request merged**
