### PR TITLE
Remove ghc-prim dependency, useless as of GHC 7.6

### PR DESCRIPTION
**Pull request by k0ral**
Cf  #7 .

### CODE REVIEW

**Comment by Gabriella439** [comment]
Awesome!  Thanks for taking the time to do that! :)

**Comment by Gabriella439** [comment]
I'll upload this to Hackage soon

**Comment by Gabriella439** [comment]
Alright, this is up on Hackage as `total-1.0.4`

**Comment by k0ral** [comment]
Thank you.
You might want to update the README file which currently shows "total-1.0.1" :) .

**Comment by Gabriella439** [comment]
Fixed!

**Pull request merged**
